name: Deploy Frontend to Azure Web App - Hotel-frontMRYSB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy frontend only
        uses: azure/webapps-deploy@v3
        with:
          app-name: Hotel-frontMRYSB
          slot-name: Production
          package: frontend
          
